[package]
name = "proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
tracy-client = { version = "0.19", default-features = false, features = ["enable", "only-localhost"] }

bytes = "1"
futures-util = { version = "0.3", features = ["sink"] }
openssl = "0.10"
tokio = { version = "1", features = ["full"] }
zerocopy = "0.8"

indexmap = "2"
uuid = "1"

ascalon-assets = { path = "../../assets" }
ascalon-network = { path = "../../network" }
ascalon-protocol = { path = "../../protocol" }
ascalon-protocol-schema = { path = "../../protocol-schema" }
